# Generated by Django 3.1.2 on 2020-10-18 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='product short description'),
            preserve_default=False,
        ),
    ]
