# Generated by Django 3.1.2 on 2020-12-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201226_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slider_image',
            field=models.ImageField(blank=True, upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='images',
            field=models.FileField(upload_to='images/'),
        ),
    ]
