# Generated by Django 3.1.2 on 2020-12-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201226_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slider_image', models.ImageField(blank=True, upload_to='static/images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='slider_image',
        ),
        migrations.AddField(
            model_name='itemimage',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
