# Generated by Django 3.1.2 on 2020-12-31 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201226_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Salon'), ('SW', 'Cuisine'), ('OW', 'Chambre')], max_length=2),
        ),
    ]
