# Generated by Django 3.1.2 on 2021-01-19 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210119_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category_number',
            field=models.CharField(choices=[('S', '1'), ('SW', '2'), ('OW', '3')], default=(('S', 'Salon'), ('SW', 'Cuisine'), ('OW', 'Chambre')), max_length=2),
        ),
    ]
