# Generated by Django 3.1.2 on 2021-01-19 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_item_category_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category_number',
            field=models.CharField(choices=[('S', '1'), ('SW', '2'), ('OW', '3')], default='S', max_length=2),
        ),
    ]
