# Generated by Django 3.1.2 on 2021-01-19 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210119_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category_number',
        ),
    ]
