# Generated by Django 3.1.2 on 2021-01-21 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_item_category_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Salon'), ('SW', 'Cuisine'), ('OW', 'Chambre'), ('AU', 'Autre')], max_length=2),
        ),
    ]
