# Generated by Django 3.1.2 on 2021-01-25 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210121_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='inventory',
            field=models.CharField(choices=[('P', 'Disponible'), ('D', 'Indisponible')], default='P', max_length=2),
        ),
        migrations.AddField(
            model_name='item',
            name='product_category',
            field=models.CharField(choices=[('MT', 'Meuble TV'), ('TM', 'Table à manger'), ('T', 'Table'), ('RA', 'Rangement'), ('C', 'Cuisine'), ('BU', 'Bureau')], default='RA', max_length=3),
        ),
        migrations.AddField(
            model_name='itemimage',
            name='caption',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='home',
            name='slider_image',
            field=models.ImageField(blank=True, upload_to='home/images/'),
        ),
    ]
